[build]
  # Your static site (index.html, assets/) lives under "supplements"
  publish = "supplements"
  command = ""

[functions]
  # Tell Netlify where your functions live
  directory = "supplements/netlify/functions"
  node_bundler = "esbuild"

# Optional: lets you also call /api/coach_llm if you prefer that path later
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
